# Generated by Django 4.1.1 on 2022-09-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Your name', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Payment description', verbose_name='Description')),
                ('price', models.FloatField(help_text='Price', verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Payer',
                'verbose_name_plural': 'Payers',
                'ordering': ['name', 'description', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='product_files/')),
                ('url', models.URLField()),
            ],
        ),
    ]
