# Generated by Django 4.1.1 on 2022-09-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name', 'description', 'price'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(help_text='Price', verbose_name='Price'),
        ),
    ]
