# Generated by Django 4.1.1 on 2022-09-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_api', '0002_alter_item_options_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('paid', models.BooleanField(default=False)),
                ('amount', models.IntegerField(default=0)),
                ('description', models.CharField(default=None, max_length=800)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name', 'description', 'price'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, help_text='Описание товара', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(help_text='Наименование товара', max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(help_text='Цена товара', verbose_name='Цена'),
        ),
    ]
